### ISSUE TITLE
If there are tasks with large files in the list, a crash will occur.

### ISSUE THREAD

**Issue by TGSAN** [Beatlegger/Transmission.API.RPC#10]
Error Message:
```
JSON integer -11644080872 is too large or small for an Int32. Path 'torrents[100].dateCreated', line 1, position 5363759.
```

So, I think we should try to use Int64 (long) instead of Int32 (int) for parameters like "time" and "file size" to avoid overflow when parsing json data.

and sorry for my poor english.

**Comment by Beatlegger** [comment]
Must be fixed https://github.com/Beatlegger/Transmission.API.RPC/commit/968dd08e06f09eff5ba6f901cc202e02f61510da
