### ISSUE TITLE
TorrentSettings fields

### ISSUE THREAD

**Issue by Beatlegger** [Beatlegger/Transmission.API.RPC#3]
Need append missing fields to **TorrentSettings.cs** and add any tests for them.

```
//"files-wanted"          | array      indices of file(s) to download
//"files-unwanted"      | array      indices of file(s) to not download
//"trackerReplace"      | array      pairs of <trackerId/new announce URLs>
//"priority-high"         | array      indices of high-priority file(s)
//"priority-low"           | array      indices of low-priority file(s)
//"priority-normal"     | array      indices of normal-priority file(s)

```

**Comment by svonidze** [comment]
I see all those fields and their descriptions were already added.
In the solution there is only one test which is an Integration one but not Unit test.
What kind of tests do you expect to be added here?

**Comment by Beatlegger** [comment]
I expect a test that will confirm the change in real parameters after calling the TorrentSet method
