### ISSUE TITLE
NuGet package Transmission.API.RPC is supplied without summary for classes, properties etc.

### ISSUE THREAD

**Issue by svonidze** [Beatlegger/Transmission.API.RPC#7]
Although (almost?) all code members are covered with summary annotation, the summary disappeared for the all members while using the NuGet. Decompiling the NuGet (with JetBrains tools) shows that indeed there is no summary. 
I can assume that NuGet is packaged manually but not automatically. @Beatlegger could you describe the approach you package the NuGet? May be that is the issue?

**Comment by Beatlegger** [comment]
Yes, I always create Nuget package manually. I was filling .nuspec file and call "nuget pack".

I don't have any experience of creating Nuget packages.

**Comment by mnieto** [comment]
@Beatlegger, could you publish the .nucspec content?

**Comment by Beatlegger** [comment]
Add xml documentation to nuget package.
https://github.com/Beatlegger/Transmission.API.RPC/commit/317e30d6735e9e88dc6fc6db7fbfc81464128e03
