### ISSUE TITLE
TorrentsGetAll method does not exists

### ISSUE THREAD

**Issue by arphox** [Beatlegger/Transmission.API.RPC#9]
Hi,

You mentioned the `TorrentsGetAll` method in the README, but I can't find it.
Can You please help how to get all torrents with the current state of the API?

Thanks a lot!

**Comment by Beatlegger** [comment]
@arphox, hi!

You can use  
```csharp
var torrents = client.TorrentGet(TorrentFields.ALL_FIELDS);
```

Readme.md updated, thx!
